# Generated by Django 4.2.3 on 2023-07-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('flat_available', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('has_paid', models.BooleanField(default=False)),
                ('move_in', models.DateField()),
                ('move_out', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_agreement', models.FileField(upload_to='files')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lease', to='homes.flat')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='properties', to='homes.property'),
        ),
        migrations.AddField(
            model_name='flat',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='homes.tenant'),
        ),
    ]
